# Generated by Django 5.2.3 on 2025-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_empresa_servico_contabil_empresa_servico_dp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_abertura',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_situacao',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_endereco',
            field=models.IntegerField(blank=True),
        ),
    ]
