# Generated by Django 5.2.3 on 2025-06-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_empresa_bairro_alter_empresa_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_situacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
