# Generated by Django 5.2.3 on 2025-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_empresa_data_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_endereco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
