# Generated by Django 5.2.3 on 2025-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_alter_empresa_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_situacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
