# Generated by Django 5.2.3 on 2025-06-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_empresa_complemento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_situacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Situação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresarial',
            field=models.CharField(max_length=255, verbose_name='Nome Empresarial'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_endereco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número (Endereço)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='servico_contabil',
            field=models.BooleanField(default=False, verbose_name='Serviço Contábil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='servico_dp',
            field=models.BooleanField(default=False, verbose_name='Serviço Departamento Pessoal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='servico_juridico',
            field=models.BooleanField(default=False, verbose_name='Serviço Júridico'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=50)),
                ('membros', models.ManyToManyField(related_name='Equipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='equipe_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empresas', to='controller.equipe'),
        ),
    ]
