# Generated by Django 5.2.3 on 2025-06-15 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_alter_empresa_cep_alter_empresa_cnpj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='equipe_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
