# Generated by Django 5.2.3 on 2025-06-21 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_alter_empresa_equipe_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='equipe_responsavel',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.equipe', verbose_name='Equipe Responsável'),
        ),
    ]
